extends Node

const amiguito: Array[String] = [
	"meow!", "~meow~", "nyaa~~", "UwU", "MEOW!!!", "OwO", "hewwo", "xD",
	"meoowww", "woeM", "purr", ":P", ":3", "m3ow", "mew", "nya", "NYAAA!!!",
	"blep", "kitty", "awoo", "arf?", "bark?", "woof?", "baka!", "m e o w",
	"∑eow", "ummm", ">.<", "*boop*", ":b", "*nuzzles*", "maullar",
	"soy una gata", "murr~", "hehe", "grrr", "*wuzzles*", "um...",
	"ummm...", "...", "-_-", "tu tu ru", "TU TU RU!!!", "mmm", "brrr meow",
	"turi turi", "~neko neko nee!~", "", "Catmmunism.",
	"All your base are belong to us >:]", "hows it goin fellas?",
	"long time no see jim", "hows the wife?", "i hate mondays",
	"just hang in there", "watch out for cucumbers", "HUNGRY!!!",
	"MEOWMEOWMEOWMEOW", "my wife left me...ow", "why do i exist?",
	"Google Murray Bookchin"
]

const big_gato: Array[String] = [
	"meow!",
	"~meow~",
	"nyaa~~",
	"UwU",
	"MEOW!!!",
	"OwO",
	"hewwo",
	"xD",
	"meoowww",
	"woeM",
	"purr",
	":P",
	":3",
	"m3ow",
	"mew",
	"nya",
	"NYAAA!!!",
	"blep",
	"kitty",
	"awoo",
	"arf?",
	"bark?",
	"woof?",
	"baka!",
	"m e o w",
	"∑eow",
	"ummm",
	">.<",
	"*boop*",
	":b",
	"*nuzzles*",
	"maullar",
	"soy una gata",
	"murr~",
	"hehe",
	"grrr",
	"*wuzzles*",
	"um...",
	"ummm...",
	"...",
	"-_-",
	"tu tu ru",
	"TU TU RU!!!",
	"mmm",
	"brrr meow",
	"", "Catmmunism.",
	"All your base\n
			are belong to...\n
			ME >:]",
	"All your base\n
			are belong\n
			to us",
	"MEOW",
	"PURR",
	"PET ME MORE HUMAN",
	"I COMMAND YOU\n
			TO PET ME!",
	"PWEASE PET ME\n
			UWU",
	"M EOW",
	"mEoW",
	"meow zedog",
	"mrowr",
	"mmm... meow",
	"hmm...",
	"M. E. O. W.",
	"YES, THIS PLEASES ME.",
	"MEOW?",
	"I AM A BIG CAT",
	"*MEOW BUT BIGGER*",
	"THEY CALL ME EL GATO\n
			NOT TO BE CONFUSED\n
			WITH THE COMPANY...",
]
