extends Node

func get_emote_library(library_name: StringName) -> Array[String]:
	if library_name == &"amiguito":
		return amiguito
	elif library_name == &"big_gato":
		return big_gato
	elif library_name == &"intro":
		return intro
	elif library_name == &"kick":
		return kick
	elif library_name == &"snare":
		return snare
	elif library_name == &"meowboy":
		return meowboy
	else:
		return [""]

var recently_used: Array[String]

const amiguito: Array[String] = [
	"xD",
	":P",
	":3",
	"UwU",
	"OwO",
	"mew",
	"nya",
	"...",
	"mmm",
	"woeM",
	"purr",
	"m3ow",
	"blep",
	"awoo",
	"arf?",
	"ummm",
	"hehe",
	"grrr",
	"meow!",
	"hewwo",
	"kitty",
	"bark?",
	"woof?",
	"baka!",
	"murr~",
	"um...",
	"*boop*",
	"MEOW!!!",
	"meoowww",
	"m e o w",
	"maullar",
	"ummm...",
	"~ meow ~",
	"nyaa ~ ~",
	"NYAAA!!!",
	"tu tu ru",
	"who am i",
	"what am i",
	"*nuzzles*",
	"*wuzzles*",
	"brrr meow",
	"turi turi",
	"HUNGRY!!!",
	"where am i",
	"TU TU RU!!!",
	"Catmmunism.",
	"soy una gata",
	"MY WIFEEE!!!",
	"want catfood",
	"CHECK PLEASE!",
	"¡Hola amigos!",
	"hows the wife?",
	"i hate mondays",
	"JAJAJAJAJAJAJA",
	"why do i exist?",
	"~ neko neko nee! ~",
	"just hang in there",
	"TERFs get the wall",
	"hows it goin fellas?",
	"long time no see jim",
	"my wife left meee...ow.",
	"watch out for cucumbers",
	"Goog le Meowrray Bonkchin",
	"and then I said 'CHECK PLS!' ",
	"MEOWMEOWMEOWMEOWMEOWMEOWMEOWMEOWMEOW",
	"...and THEN I said 'cHheCk plEaSeE!!!'",
	"¡Vengo con maullidos y mucha comida para gatos!",
	"late-stage catpilled-alism... AM I RIGHT?!",
	"must eat",
	"MUST. EAT.",
	"aNd ThEn I sAiD *inhales* CHECK PLEASE!",
	"what IS the deal with airline food?",
	"ayy i'm walkin' ova 'ere!",
	"ayy i'm meowin' ova 'ere!",
	"ayy i'm screwin' up ur sofa ova 'ere!",
	"ayy i'm ova 'ering  ova 'ere!",
	"walkin' i'm 'ere ayy ova",
	"ayy i'm a Deleuzian body without organs ova 'ere!",
	"CATCATCATCATCATCAT...",
	"KITTYKITTYKITTYKITTYKITTY...",
	"more like isn'trael",
	"free pawlistine!",
	"most days you could say I'm shuffling",
	"this is psychotic",
	"what am i doing with my life",
	"git er dun",
	"merp",
	"derp",
	"poggers",
	"i've got too much rizz",
	"skibidi toilet",
	"E",
	"big chungus",
	"i AM the one who meows, skylar! meow",
	"is this what fredric jameson was talkin about",
	"i'm a pastiche of a pastiche baby",
	"where are you? and i'm so sorry",
	"check under ur toilet seat 4 spiders",
	"yep. i am cat.",
	"Good afternoon.",
	"hOw dO yOu dO my gOOd sir?",
	"* teleports behind you *",
	"while you were partyin' I was studyin' the blade",
	"if she breathes she's a thot",
	"i got a glock in my rawri xD",
	"17 shots, no .38",
	"slaughter ur daughter",
	"UwUwUwUwUwUwUw",
	"i put the new forgios on the jeep",
	"i drive a chevrolet movie theatre",
	"interior crocodile alligator",
	"it's joever",
	"we're so barack",
	"its not joever yet",
	"i'm with HER.",
	"1312",
	"eeeck errrk",
	"we're goin to walmart",
	"wallywallywallywally WORLD"
]

const big_gato: Array[String] = [
	"MEOW",
	"PURR",
	"mEoW",
	"swag",
	"M EOW",
	"mrowr",
	"MEOW?",
	"hmm...",
	"M E O W",
	"catamari",
	"M E O  w",
	"purrhaps",
	"thug life",
	"BEEG GATO",
	"meow zedog",
	"hmmmeow...",
	"mmm... meow",
	"like a boss",
	"i'm so 2008",
	"FELINE GOOD",
	"boom boom meow",
	"ur so 2000late",
	"I AM A BIG CAT",
	"PET ME MORE HUMAN",
	"u cat'n be furreal",
	"Live. Laugh. Meow.",
	"CAN HAS CHEEZBURGER?",
	"YES, THIS PLEASES ME.",
	"Boop my snoot, or else.",
	"I COMMAND YOU TO PET ME!",
	"M E O W  B U T  B I G G E R ",
	"All your base are belong to... MEOW",
	"Still need to click for coins I see.",
	"do i have to keep saying stuff after the intro?",
	"you've CAT to be KITTEN me right MEOW! JAJAJAJJAJAJA",
	]

var intro: Array[String] = [
	## The ""'s are a break in dialogue btw
	## Couldn't think of a better way to do it lol
	"meow",
	"Hello.",
	"",
	"",
	"'round these parts...",
	"...they call me Gato",
	"meow",
	"",
	"in this game",
	"meow",
	"you collect",
	"",
	"[meows in Spanish]",
	"",
	"",
	"CATS!",
	"",
	"oh look",
	"",
	"heh",
	"hey there lil guy",
	"",
	"mreowr...",
	"",
	"and give them...",
	"",
	"uhhh...",
	"",
	"...",
	"hats?",
	"",
	"idk...",
	"",
	"so, yeah",
	"meow",
	"have fun",
	"",
	"now give that back",
	]

var meowboy: Array[String] = [
	"M'eow lady...",
	"Dammit Dutch!",
	"Meowdy, pawdner.",
	"Excuse meow, miss",
	"Hey there cowpoke",
	"Outlaws Fur Life.",
	"Hands to the sky!",
	"WHAT IN TARNATION",
	"Yep. Sure is nice.",
	"You, sir, are a fish.",
	"Just one meowr score.",
	"all them years, dutch...",
	"Name's Arthpurr Meowgan.",
	"THARS A SNAKE IN MEOW BOOT",
	"wHERE's thAt DaMN H~O~R~S~E",
	"We're meow ghosts than people...",
]

var kick: Array[String] = [
	"BOOTS",
	"BOOTS 'n'",
	"BOOM",
	"THUD"
]

var snare: Array [String] = [
	"CATS",
	"CRASH",
	"KSHHH",
	"PSHHH",
]
